### ISSUE TITLE
Sync: GIST NOT SAVED when uploading settings to gist

### ISSUE THREAD

**Issue by taigi100** [shanalikhan/code-settings-sync#1039]
🐛 **Describe the bug**  
I'm trying to set up my sync, used to work find but today I noticed I'm getting the following error when trying to upload settings:
![image](https://user-images.githubusercontent.com/10900362/64626130-04f39a80-d3f6-11e9-9d34-b943093bc603.png)

🌴 **Visual Studio Code Version :** [ 1.38 ] 
🌴 **Code Settings Sync Version :** [3.4.2 ] 
🌴 **Operating System :** [ Windows 10 ] 
🌴 **Occurs On:** [Upload]
🌴 **Proxy Enabled:** [ No ]
🌴 **Gist Id:** [0ff283486d00810e5af0740e91352207]

**Comment by vcorreia** [comment]
Hello,

I'm having the same issue:

![image](https://user-images.githubusercontent.com/324151/64686367-77a95800-d480-11e9-8e75-1ffe3d5bf862.png)

Version: 1.38.0 (user setup)
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:49:13.459Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by vcorreia** [comment]
Has anyone experienced the same issue?

**Comment by vcorreia** [comment]
I have uninstalled and reinstalled the extension, even creating a new GIST, but to no avail.

**Comment by shanalikhan** [comment]
It should be fixed on the latest version of Settings Sync `v3.4.3`. Let me know if it persist. I will reopen this issue.

**Comment by vitorhmcorreia** [comment]
Hey!

I've installed the updated version but unfortunately, the error persists:

![image](https://user-images.githubusercontent.com/324151/65430713-3fa2fd00-de10-11e9-9358-5f67b02e5d23.png)

Should I completely remove the extension and try again?
Is there any "special" procedure I should follow?

Best regards.

**Comment by shanalikhan** [comment]
Try removing the extension and restarting the code and installing extension. Then reset the extension settings and try to upload on new gist.

@vcorreia

**Comment by vitorhmcorreia** [comment]
> Try removing the extension and restarting the code and installing extension. Then reset the extension settings and try to upload on new gist.
> 
> @vcorreia

Followed your steps, but got the same error:

![image](https://user-images.githubusercontent.com/324151/65431315-2ea6bb80-de11-11e9-920c-bc762e390fba.png)

**Comment by shanalikhan** [comment]
Okay, can you upload your `Users` folder in compressed form ( removing confidential things) so i will try to reproduce it later?
I will update the GitHub api too to the latest version as a part of next release of Settings Sync.

**Comment by vitorhmcorreia** [comment]
Which folder, exactly?
I'm using a corporate machine, due to group policies I don't have access to all folders.

**Comment by taigi100** [comment]
I've also updated to latest version, and check it out. Same error as @vcorreia. I'm on a personal machine so I don't have corporate issues. I'm working from a windows machine and not sure which folder you want?

**Comment by vitorhmcorreia** [comment]
Hello everyone,

I've been caught up by work and have not had a chance to see if the issue had any updates.
@taigi100 , have you had any luck syncing your settings?

**Comment by shanalikhan** [comment]
>  I'm using a corporate machine, due to group policies I don't have access to all folders.

@vcorreia and @taigi100 
`User` folder contains your `settings.json` and other files. I like to reproduce this error on the files you have. So you need to share the folder in compressed form (you can remove the confidentials files)

**Comment by taigi100** [comment]
@vcorreia nope, still not working

@shanalikhan mentioned of a `User` folder. With some googling I think he is referring to `%AppData%/Code/User`.
I have attached my settings.json and syncsettings below

[User.zip](https://github.com/shanalikhan/code-settings-sync/files/3686635/User.zip)

**Comment by jtuttas** [comment]
I have exact the same Problem, with a german error message.

Because I used the Profile Switcher Extension (aaronpowell.vscode-profile-switcher) my settings.json is about 966 Lines long. May be this could caused the problem?

**Comment by jtuttas** [comment]
@taigi100 I can see that u uses this extension too !

@shanalikhan can this be the problem? Is there a max size for a gist?

**Comment by jtuttas** [comment]
Yeah, after removing the extension everything works likes expected ! :-) !

**Comment by shanalikhan** [comment]
> Because I used the Profile Switcher Extension (aaronpowell.vscode-profile-switcher) my settings.json is about 966 Lines long.

What really is there in 966 lines of configurations?

I have to see how GitHub limit users in Gist in terms of length.

**Comment by taigi100** [comment]
@jtuttas @shanalikhan
I've created a test gist: https://gist.github.com/taigi100/71a1a13f1cbeff5a818b7ae47731dd52
It's bigger (~ 40k lines) seems to work well.
Maybe it's an upload size issue? Some timeouts? I don't know.

**Comment by zed-dz** [comment]
"This gist exceeds the recommended number of files (~10). To access all files, please clone this gist. To share more, create a repository."

![image](https://user-images.githubusercontent.com/30353760/66667365-c6e2d400-ec4a-11e9-8dd4-a1353390ba2e.png)

**Comment by vitorhmcorreia** [comment]
Guys,

After removing the extension Profile Switcher Extension, I was also able to sync properly!

**Comment by vitorhmcorreia** [comment]
> Guys,
> 
> After removing the extension Profile Switcher Extension, I was also able to sync properly!

Spoke too soon...
First sync worked, but the next did not.

I deleted my gists and did a settings reset. Was able to sync properly the first time, but after that it fails again. 

It sure seems to be hitting some sort of upload limit. If I delete the only GIST I have for code-settings and try to upload, it works (for the first run).

**Comment by mcollier** [comment]
FYI - Removal of Profile Switcher seemed to resolve the problem for me.

**Comment by taigi100** [comment]
@vcorreia @mcollier 
In my case deleting profile switcher isn't really an option, looked a long time for it. The combination of sync and profile switcher was amazing tho.

**Comment by shanalikhan** [comment]
Can you guys open issue on Profile Switcher and let author know about it, linking this issue.

I have tried on Ubuntu, Windows and its working perfectly. I will try to spend some time on it later on.

**Comment by mcollier** [comment]
@shanalikhan I'm going to try some more.  Likely re-enabling Profile Switcher and observe results. The challenge I'm having is understanding _why__ Settings Sync is unable to save.  Is there a way to get more detailed debugging information from Settings Sync that may show what failed?  For example, is there a way to see the error coming from GitHub, as @Zed-M suggested earlier?

**Comment by vitorhmcorreia** [comment]
> Can you guys open issue on Profile Switcher and let author know about it, linking this issue.
> 
> I have tried on Ubuntu, Windows and its working perfectly. I will try to spend some time on it later on.

Thank you for your investment on this issue.
I have tried all combinations, including a fresh vscode installation, with only sync extension installed and even that has not worked :|

**Comment by shanalikhan** [comment]
> I will try to spend some time on it later on.

@mcollier and @taigi100 

Can you guys provide me concrete steps to reproduce it (including installing profile switcher). I will get the settings from https://github.com/shanalikhan/code-settings-sync/issues/1039#issuecomment-537976629

> I have tried all combinations, including a fresh vscode installation, with only sync extension installed and even that has not worked :|

@vcorreia

Are you getting this same exception on event fresh install and Settings Sync configured. Can you post your console logs?

**Comment by taigi100** [comment]
@shanalikhan I'm not sure I would be able to provide some exact steps. It's one of those bugs that seemed to work find and then suddenly stopped working. I'll try to check it out more in depth after I'm done with some current projects I'm working on.

**Comment by aaronpowell** [comment]
👋  Howdy all, author of Profile Switcher here.

Let me know what I can do to help debug/resolve this. If it seems there's a problem that the max size of a gist is being hit (is there a max size, I'm unsure) I'll have to think more creatively around how the extensions are tracked for profiles. (I'm aware that the extension tracking support I added caused the `settings.json` file to explode in size.)

**Comment by jpsantos7** [comment]
@shanalikhan I don't have profile-switcher and I still get the error.

> "This gist exceeds the recommended number of files (~10). To access all files, please clone this gist. To share more, create a repository."
> 
> ![image](https://user-images.githubusercontent.com/30353760/66667365-c6e2d400-ec4a-11e9-8dd4-a1353390ba2e.png)

If I remove the gist and upload again it creates a new one, but on the second upload it fails again.

**Comment by vitorhmcorreia** [comment]
> @shanalikhan I don't have profile-switcher and I still get the error.
> 
> > "This gist exceeds the recommended number of files (~10). To access all files, please clone this gist. To share more, create a repository."
> > ![image](https://user-images.githubusercontent.com/30353760/66667365-c6e2d400-ec4a-11e9-8dd4-a1353390ba2e.png)
> 
> If I remove the gist and upload again it creates a new one, but on the second upload it fails again.

Same here. I've been using code-settings this way, by deleting the first gist and uploading again...

**Comment by pegasi51b** [comment]
I had the same issue, to solve this problem I add `"aaronpowell.vscode-profile-switcher"` to list of folders ignored during upload to gist. Settings can be found in `%AppData%/Code/syncLocalSettings.json`.

**Comment by dougwaldron** [comment]
I had the same issue, but with the [webhint](https://marketplace.visualstudio.com/items?itemName=webhint.vscode-webhint) extension. This extension adds the folder `webhint.vscode-webhint/node_modules/` to the User `globalStorage` folder, which seems like a mistake. Maybe profile-switcher is doing the same thing?

The `node_modules` folder contains dozens (hundreds?) of JSON files, which all get uploaded causing the gist to get locked by GitHub.

Maybe a universal fix would be adding `node_modules` to the default list of ignored folders.

**Comment by jabacchetta** [comment]
Yeah, with Profile Switcher, both `settings.json` and `globalStorage` can become massive.

**Comment by mcandre** [comment]
:(

**Comment by snowyu** [comment]
Add `node_modules` to the `ignoreUploadFolders`, now all work again. 

code `~/.config/Code/User/syncLocalSettings.json`

```js
{
    "ignoreUploadFolders": [
        "node_modules",
        "workspaceStorage"
    ],

```

**Comment by xiaoyang-chen** [comment]
it maybe be cause by this (https://github.com/shanalikhan/code-settings-sync/issues/1039#issuecomment-549186953),
I find %AppData%/Code/History is massive, and then add "History" into syncLocalSettings.json
```json
"ignoreUploadFolders": [
    "History",
    "workspaceStorage"
],
```
after add it, settings sync work again

**Comment by FranciscoHuchinUc** [comment]
> ```json
> "History",
>     "workspaceStorage"
> ```

Esto me funciono correctmente al dia de hoy

**Comment by xshapira** [comment]
> it maybe be cause by this ([#1039 (comment)](https://github.com/shanalikhan/code-settings-sync/issues/1039#issuecomment-549186953)), I find %AppData%/Code/History is massive, and then add "History" into syncLocalSettings.json
> 
> ```json
> "ignoreUploadFolders": [
>     "History",
>     "workspaceStorage"
> ],
> ```
> 
> after add it, settings sync work again



> Add `node_modules` to the `ignoreUploadFolders`, now all work again.
> 
> code `~/.config/Code/User/syncLocalSettings.json`
> 
> ```js
> {
>     "ignoreUploadFolders": [
>         "node_modules",
>         "workspaceStorage"
>     ],
> ```

@xiaoyang-chen, @snowyu 

Thank you, guys. Super helpful!

**Comment by luong-komorebi** [comment]
For this to work again, please remove the old gist, add History to the ignored Folders 
![image](https://user-images.githubusercontent.com/15828926/194835371-02ae548b-d1ce-4360-8667-561d6ab12a9b.png)
And then tirgger an upload again

This failure is because of the size of the history folder, which makes Github Gist API returns with a failure. This feature was release sometimes ago in 1.66 version (called Local History). The reason some people are recently seeing errors is because the folder just got bigger than what Github can handle

**Comment by estebangarviso** [comment]
I've added node_modules and History to ignored Folders, and it worked.
