### ISSUE TITLE
Connection TimedOut on trying to upload settings

### ISSUE THREAD

**Issue by hellt** [shanalikhan/code-settings-sync#253]
**Visual Studio Code Version :** [ 1.10.1 ]
**Code Settings Sync Version :** [ 2.5.1 ]
**Operating System :** [ WIN7 ]
**Occurs On:** [Upload ]
**Proxy Enabled:** [ Yes]
**GIst Id:** [ ID_HERE ]

```
[Extension Host] Error: connect ETIMEDOUT 192.30.253.116:443
    at global.sendError (C:\Users\rdodin\.vscode\extensions\Shan.code-settings-sync-2.5.1\node_modules\github\lib\index.js:838:19)
    at C:\Users\rdodin\.vscode\extensions\Shan.code-settings-sync-2.5.1\node_modules\github\lib\index.js:849:29
    at callCallback (C:\Users\rdodin\.vscode\extensions\Shan.code-settings-sync-2.5.1\node_modules\github\lib\index.js:713:17)
    at ClientRequest.<anonymous> (C:\Users\rdodin\.vscode\extensions\Shan.code-settings-sync-2.5.1\node_modules\github\lib\index.js:791:17)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
```

I believe it has smth to do with proxy server I have. How to check things further?

**Comment by shanalikhan** [comment]
I wont be able to reproduce this error due to proxy environment settings.
Previously users sent me pull request to solve the proxy issues.

If you have time, you can download the code by placing the commands written here , you can debug this the extension and send me pull request, i will accept that and hopefully extension will be more compatible with proxy environments.
https://github.com/shanalikhan/code-settings-sync#through-code

**Comment by hellt** [comment]
Is there a way to check what proxy settings this extension is trying to use in my environment?
Because if it uses VS Code settings then it is strange, since VS code can download packages without problems.

**Comment by shanalikhan** [comment]
This error is actually coming from Github API from extension. Github API doenst understand your proxy environment.
I have pushed an update for Code Insiders, with newer version for github API.
Would you test over there if there is same exception ?

**Comment by hellt** [comment]
I didnt try the Code Insiders thing you mentioned, but the recent release in stable branch did not fix the issue for me. Which is quite strange I have to admit

**Comment by shanalikhan** [comment]
@hellt i am not able to reproduce this issue as its is network dependent issue.
What you can do it download the source code and send me pull request, i will accept that

**Comment by shanalikhan** [comment]
I have fixed the request settings on another issue, so i wanted to ask that is this issue fixed ? or you can still getting exception on 2.8.3 ?
