### ISSUE TITLE
The "open issues" and "release notes" buttons do not work

### ISSUE THREAD

**Issue by elboletaire** [shanalikhan/code-settings-sync#289]
**Visual Studio Code Version :** 1.11.1
**Code Settings Sync Version :** 2.6.2
**Operating System :** Ubuntu 16.04
**Occurs On:** Upload
**Proxy Enabled:** No

Both options available under `advanced options` do nothing.

**Comment by shanalikhan** [comment]
is there any exception in developer console.

**Comment by elboletaire** [comment]
Nothing at all.

**Comment by elboletaire** [comment]
In fact, I've just installed `Settings sync` on a new computer, and none of the buttons from the top banners work either.

**Comment by shanalikhan** [comment]
Ok, i will check it out in ubuntu environment soon and work on it :)

**Comment by shanalikhan** [comment]
It should be fixed in v2.8
Let me know if there is problem

**Comment by elboletaire** [comment]
Nope, it's not fixed. But at least now it throws errors to the console:

![imatge](https://cloud.githubusercontent.com/assets/153305/26371173/3d36619e-3ffa-11e7-8818-7d2878f01ce2.png)

In this case the button I clicked was the "donate" button, but all the buttons that appeared failed opening their links.

This issue should be reopened.

**Comment by ryansully** [comment]
Sort of side note, but could Release Notes be mirrored to the Changelog tab in the extension pane as well?

**Comment by shanalikhan** [comment]
Extension read me page is already very long and detailed, its better to keep the change log in separate page. What can be done is only the current version details can be shown in the change log section.

**Comment by shanalikhan** [comment]
Fixed in v2.8.1
