### ISSUE TITLE
Can't update/upload sync settings to github while behind corporate decrypting firewall

### ISSUE THREAD

**Issue by duanehutchins** [shanalikhan/code-settings-sync#376]
**Visual Studio Code Version :** 1.15.0-insider
**Code Settings Sync Version :** v2.8.2
**Operating System :** Windows 8.1 x64
**Occurs On:** Upload
**Proxy Enabled:** No
**GIst Id:** 307d973536d31e02d71bea8c34d51476

**Issue:** Can't update sync settings behind corporate decrypting firewall with a self signed cert. This is because the https post request is not allowed through with a self-signed CA. I do not use a proxy, but I do have `http.proxyStrictSSL` set to `false`

* Upload fails when behind a decrypting firewall
* Download succeeds with or without the firewall

![image](https://user-images.githubusercontent.com/1530028/29030378-c6839d10-7b58-11e7-8614-18c596d03f61.png)

**Expected Result:** With `http.proxyStrictSSL` set to `false`, code-settings-sync should not be verifying the github CA.

If it helps, this issue is similar to Microsoft/vscode#11702 (fixed in Microsoft/vscode@31f0a33)

**Comment by Fenweldryn** [comment]
same issue here.
```
[Extension Host] Error: connect ECONNREFUSED 
[Extension Host] Empty value for parameter 'id': 
```

**Comment by rdlaner** [comment]
I'm having the same issue, I'm prevented from both uploading and downloading.

**Comment by ephillipe** [comment]
I'm too not Uploading. Download works well, bot not Upload.

**Comment by shanalikhan** [comment]
There is similar issue opened https://github.com/shanalikhan/code-settings-sync/issues/219
for which i fixed for download. Upload is pending.

**Comment by shanalikhan** [comment]
I have fixed this issue in the last update
let me know if its working for you.

**Comment by Fenweldryn** [comment]
trying to shift+alt+u (through command console, shortcut not working) but still getting errors.

```
[Extension Host] Error: connect ECONNREFUSED        workbench.main.js:29
[Extension Host] Empty value for parameter 'id':         workbench.main.js:29 
GET https://shan.gallerycdn.vsassets.io/extensions/shan/code-settings-sync/2.8.3/1503229495713/Microsoft.VisualStudio.Services.Content.Details 200 ()
```

**Comment by ImJoeHs** [comment]
May I ask if anyone has resolved this problem?

**Comment by duanehutchins** [comment]
No. It's still not resolved for me.

**Comment by shanalikhan** [comment]
**PR is welcome**
I tried to completed all the things that were required (as per packages documentation).
Some one can send me PR and i will release new version.

**Comment by duanehutchins** [comment]
This still isn't working.  Sorry.

I found this today though: Microsoft/vscode#12588, so vscode doesn't yet support proxy settings in extensions.
