### ISSUE TITLE
code snippets not being synced after update to 3.3.0

### ISSUE THREAD

**Issue by pr4shan7** [shanalikhan/code-settings-sync#927]
🐛 **Describe the bug**  
The code snippets are not being synced after update to 3.3.0 earlier today. Also, I noticed that the existing snippets file in my private gist got deleted after the first upload post updating to 3.3.0
Everything else is syncing fine.

🌴 **Visual Studio Code Version :** [ 1.35.1 ] 
🌴 **Code Settings Sync Version :** [ 3.3.1 ] 
🌴 **Standard or Insiders :** [ Standard ] 
🌴 **Portable or Installed :** [ Installed ] 
🌴 **OSS or Official Build :** [ Official Build ] 
🌴 **Operating System :** [ Ubuntu 18.04.2 LTS ] 
🌴 **Occurs On:** [Upload ]
🌴 **Proxy Enabled:** [ No ]

📰 **To Reproduce**
1. Run sync from the command palette

💪 **Expected behavior**
Code snippets file is not synced; also the snippets file does not exist in the gist.

📺 **Console Error Log** 
None

📺  **Additional context**
Part of the summary page:

```
Files Uploaded:
  extensions.json > extensions.json
  keybindings.json > keybindings.json
  settings.json > settings.json

**Comment by luizgdi** [comment]
Same problem here

**Comment by arnohovhannisyan** [comment]
Please try this updated version: https://cdn.discordapp.com/attachments/549007146868539408/593147029165965322/code-settings-sync-3.3.1.vsix

Instructions: https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

**Comment by luizgdi** [comment]
Installed the .vsix, now I'm getting the error:  "Sync: Error Logged In Console (Help menu > Toggle Developer Tools)."

**Comment by luizgdi** [comment]
@arnohovhannisyan Problem persists here in 3.3.1.vsix

**Comment by arnohovhannisyan** [comment]
@luizgdi Can you please show the console output? Go to `Help -> Toggle Developer Tools` and send a screenshot of it.

**Comment by SimonGolms** [comment]
![image](https://user-images.githubusercontent.com/17799657/60126472-5f357580-978e-11e9-87e1-edaa8fdd6220.png)

**Comment by luizgdi** [comment]
![sync](https://user-images.githubusercontent.com/43801004/60126781-246b1780-9765-11e9-96ba-cfa7d866b75a.png)
@arnohovhannisyan

**Comment by arnohovhannisyan** [comment]
@luizgdi This version should fix that: https://cdn.discordapp.com/attachments/549007146868539408/593317522242011147/code-settings-sync-3.3.1.vsix

**Comment by luizgdi** [comment]
@arnohovhannisyan Yes! Fixed in this version, thanks!!

**Comment by Calvin-Newton-UNC** [comment]
@arnohovhannisyan
I installed the new version but still get error
![Capture1](https://user-images.githubusercontent.com/32373659/60201295-8aab7500-980d-11e9-835c-cb398b4cc8af.PNG)
![Capture2](https://user-images.githubusercontent.com/32373659/60201318-9860fa80-980d-11e9-9caf-7159a065b091.PNG)

**Comment by arnohovhannisyan** [comment]
@Calvin-Newton-UNC Can you make sure that the gist id is correct? You might have swapped the gist id and token.

**Comment by Calvin-Newton-UNC** [comment]
I get this error when trying to do Sync: Update/Upload Settings. 

Here are the steps:
If I reset the extension settings with Sync: Reset Extension Settings and try to upload again it prompts for the access token
![Capture3](https://user-images.githubusercontent.com/32373659/60206959-73bf4f80-981a-11e9-9e66-256b67f48a17.PNG)
If I generate a new token and copy it to the prompt I get the same error. My token looks like 5e5d4758a9450a288e3e3dc3f0b7bbd09b530acb

**Comment by arnohovhannisyan** [comment]
@Calvin-Newton-UNC Have you added the `gist` option when creating the token? If so, then this is an issue with the gist id, not the token. Try going to https://gist.github.com and finding your gist. Then copy the id from the URL (it should look like the token). Go into your VSCode settings and paste it into the `sync.gist` setting.

**Comment by robjvan** [comment]
Still not uploading snippets for me either... Confirmed Gist id is good, and can see upload revisions in the Gist online, but no snippet files being uploaded.  

Same problem as above - update deleted the snippets that were already in the gist and being backed up, and I haven't been able to upload them since.

**Comment by arnohovhannisyan** [comment]
@robjvan Have you tried this version? https://cdn.discordapp.com/attachments/549007146868539408/593317522242011147/code-settings-sync-3.3.1.vsix

**Comment by JtMotoX** [comment]
@arnohovhannisyan Thank you!!  I was experiencing the same problem and found this open issue.  I was using 3.3.1 which was updated through Code but after manually installing your 3.3.1 it is now uploading my snippets to my gist.  I have installed that vsix on all my systems.  Thanks again.

**Comment by LABCAT** [comment]
I also have this issue. I have tried uninstalling settings sync and reinstalling from the vsix file at the link above.  I also reset the "Settings Sync" settings to see if that would help but snippets still not showing in my gist.

Is there anything else I can try?

**Comment by sunhs** [comment]
Problem still exists with these steps:
- Sync: Reset extension settings
- Uninstall Sync
- Reinstall Sync from vsix

Here's my environment:
```
Version: 1.35.1 (user setup)
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:30:02.622Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```

**Comment by yuritoledo** [comment]
3.3.1 still not working.

3.2.9 it's ok.

**Comment by through-a-haze** [comment]
Had version 3.3.1 and it didn't work for me.
Didn't uninstall but simply reinstalled version 3.3.1 from the .vsix file above and now it works.

**Comment by marjorg** [comment]
@arnohovhannisyan I'm on 1.36.0 and it doesn't seem to sync snippets. It's the first time I try to sync snippets, so I'm not sure if it has worked previously. I can't see any errors in dev tools console.

```
Files Uploaded:
  extensions.json > extensions.json
  keybindings.json > keybindingsMac.json
  settings.json > settings.json
```

**Comment by arnohovhannisyan** [comment]
@marjorg Have you tried this? https://cdn.discordapp.com/attachments/549007146868539408/593317522242011147/code-settings-sync-3.3.1.vsix

**Comment by robjvan** [comment]
Solved by switching to "syncing" extension, does the same thing but hasn't deleted my previously created snippets as of yet.

**Comment by pr4shan7** [comment]
@robjvan Just curious, is the snippet file still present in your gist on GitHub, or has it been deleted likewise? Only the snippet file in my gist was deleted while the file was still present on my local system after the upload.

**Comment by marjorg** [comment]
> @marjorg Have you tried this? https://cdn.discordapp.com/attachments/549007146868539408/593317522242011147/code-settings-sync-3.3.1.vsix

@arnohovhannisyan Nice, that works for me. Thanks!

**Comment by yubaoquan** [comment]
So how to get the deleted snippet files back?

**Comment by shanalikhan** [comment]
Here are the steps to get back to older version of GIST

[How to Revert to an earlier GIST](https://github.com/shanalikhan/code-settings-sync/wiki/Troubleshooting#how-to-revert-to-an-earlier-gist)

**Comment by shanalikhan** [comment]
v3.4.0 is released and this has been fixed.
Update the extension and let me know if there is any issue.
